(function(H){'use strict';
let ctx,masterGain,timer,n=0,settings=H.defaultSettings,volume=.5;
const key='homeyear.audio.volume.v1',melody=[261.63,329.63,392,329.63,293.66,349.23,440,392,329.63,392,523.25,440,349.23,293.66,261.63,196];
try{const raw=localStorage.getItem(key);if(raw!==null){const v=JSON.parse(raw);if(typeof v==='number'&&Number.isFinite(v)&&v>=0&&v<=1)volume=v;}}catch(e){}
function tone(f,d=.15,v=.05){if(!ctx||ctx.state!=='running')return;const o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(0,ctx.currentTime);g.gain.linearRampToValueAtTime(v,ctx.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+d);o.connect(g);g.connect(masterGain);o.start();o.stop(ctx.currentTime+d+.02);}
function music(){if(!settings.music||!ctx||document.hidden){clearInterval(timer);timer=null;return;}if(!timer)timer=setInterval(()=>tone(melody[n++%melody.length],.6,.018),650);}
H.Audio={unlock(){try{if(!ctx){ctx=new(window.AudioContext||window.webkitAudioContext)();masterGain=ctx.createGain();masterGain.gain.value=volume;masterGain.connect(ctx.destination);}ctx.resume().then(()=>{if(settings.music)music();}).catch(()=>{});if(settings.music)music();}catch(e){}},configure(s){settings=s;if(!s.music){clearInterval(timer);timer=null;}if(s.music||s.sound){if(ctx)ctx.resume().then(()=>{if(settings.music)music();}).catch(()=>{});if(s.music)music();}else if(ctx)ctx.suspend().catch(()=>{});},volume:()=>volume,setVolume(v){if(typeof v!=='number'||!Number.isFinite(v)||v<0||v>1)return false;volume=v;if(masterGain)masterGain.gain.setValueAtTime(v,ctx.currentTime);try{localStorage.setItem(key,JSON.stringify(v));}catch(e){}return true;},status:()=>({volume,gain:masterGain?masterGain.gain.value:null,state:ctx?ctx.state:'uncreated',musicRunning:!!timer}),play(kind){if(!settings.sound)return;const notes={buy:[330,392],sell:[392,523],next:[262,330],house:[262,330,392,523],error:[180,150],news:[440,349],click:[330]}[kind]||[330];notes.forEach((f,i)=>setTimeout(()=>{if(settings.sound)tone(f,.18,.04);},i*90));}};
document.addEventListener('visibilitychange',music);
})(window.HomeYear);
