(function (H) {
  'use strict';
  const marketEvents = H.events.filter(e => e.type === 'market');
  const personalEvents = H.events.filter(e => e.type === 'personal');
  const pick = (s,list) => list[Math.floor(H.random(s,'events') * list.length)];
  H.environment = s => {
    s.season = H.seasonAt(s.week);
    // Mild macro inertia; no income is generated by waiting.
    s.macro = Math.max(.8,Math.min(1.2,s.macro * .8 + (.9 + .2 * H.random(s,'market')) * .2));
  };
  H.drawEvents = s => {
    s.activeEvents = s.activeEvents.filter(e => e.until >= s.week);
    s.personal = 0;
    s.personalEvent = null;
    s.news = [];
    if (H.random(s,'events') < .42) {
      const e = pick(s,marketEvents);
      if (!s.activeEvents.some(a => a.id === e.id)) {
        s.activeEvents.push({id:e.id, started:s.week, until:s.week + e.duration - 1});
      }
    }
    // Roughly four personal events per year. Risk scales costs, not trade profit.
    if (H.random(s,'events') < .08) {
      const e = pick(s,personalEvents);
      s.personalEvent = e.id;
      s.personal = e.cash < 0 ? Math.round(e.cash * H.difficulty(s).risk) : e.cash;
    }
  };
  H.trends = s => {
    for (const p of H.products) {
      const m = s.market[p.id];
      m.trend = m.trend * .7 + (H.random(s,'market') - .5) * p.volatility;
    }
  };
  H.prices = s => {
    for (const p of H.products) {
      const m = s.market[p.id];
      const level = s.activeEvents.reduce((n,a) => {
        const e = H.events.find(e => e.id === a.id);
        return n + (e.effects[p.id] || 0) * p.eventSensitivity;
      },0);
      const seasonal = 1 + p.season * Math.cos((s.week-1)/52 * Math.PI * 2 + p.phase);
      const target = p.base * seasonal * s.macro * Math.max(.2,1 + level);
      const shock = (H.random(s,'market')-.5) * p.volatility * H.difficulty(s).volatility;
      m.previous = m.price;
      m.price = H.int(Math.max(p.min,Math.min(p.max,Math.round(
        m.price + .22 * (target-m.price) + m.price * (m.trend * p.trendSensitivity + shock)
      ))));
      m.history.push(m.price);
      if (m.history.length > 12) m.history.shift();
      m.low = Math.min(m.low,m.price);
      m.high = Math.max(m.high,m.price);
    }
  };
  H.personal = s => {
    if (s.personal < 0) {
      const paid = Math.min(s.cash,-s.personal);
      s.cash -= paid;
      s.stats.hardship = H.add(s.stats.hardship,-s.personal-paid);
      s.stats.expenses = H.add(s.stats.expenses,paid);
    } else {
      s.cash = H.add(s.cash,s.personal);
      s.stats.grants = H.add(s.stats.grants,s.personal);
    }
  };
  H.news = s => {
    s.news = s.activeEvents.map(a => {
      const e = H.events.find(e => e.id === a.id);
      return {id:e.id, title:e.title, reliability:e.reliability, week:s.week};
    });
    if (s.personalEvent) {
      const e = H.events.find(e => e.id === s.personalEvent);
      s.news.push({id:e.id,title:e.title,reliability:'reliable',week:s.week});
    }
    // A rumor does not instantiate a market event. It may be true or false;
    // accuracy tags describe the source, never disclose hidden active effects.
    if (H.random(s,'events') < .3) {
      const p = H.products[Math.floor(H.random(s,'events')*H.products.length)];
      const up = H.random(s,'events') > .5;
      s.news.push({id:'rumor', title:p.name+'需求或将'+(up?'增加':'转弱')+'（未经证实）', reliability:'rumor', week:s.week});
    }
  };
})(window.HomeYear);
