'use strict';
const fs=require('node:fs/promises'),path=require('node:path'),{spawn}=require('node:child_process'),{pathToFileURL}=require('node:url');
const {launchEdge,CDP,getJSON,delay}=require('./cdp-helper.cjs');
(async()=>{
 const dir=path.join(__dirname,'../docs/'+(process.env.ACCEPTANCE_DIR||'acceptance-evidence'));await fs.mkdir(dir,{recursive:true});
 const report={kind:'real Edge headless file:// DOM automation; not manual play',checks:[],errors:[],requests:[],performance:[],fixtures:'Public JSON import; cash grants are non-natural economy',started:new Date().toISOString()};let edge,c,restarted;
 const url=pathToFileURL(path.join(__dirname,'../index.html')).href;
 const ev=x=>c.evaluate(x),snap=()=>ev('HomeYear.UI.snapshot()');
 async function ck(name,fn){try{const result=await fn();if(!result)throw Error('assertion false');report.checks.push({name,pass:true});}catch(e){report.checks.push({name,pass:false,error:e.message});console.error(name,e.message);}}
 async function click(selector){await ev(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});if(!e)throw Error('Missing '+${JSON.stringify(selector)});if(e.disabled)throw Error('Disabled '+${JSON.stringify(selector)});e.click()})()`);await delay(260);}
 async function input(selector,value){await ev(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}))})()`);}
 async function close(){if(await ev('document.querySelector("dialog").open'))await click('[data-action=close]');}
 async function load(){await c.send('Page.navigate',{url});for(let i=0;i<100;i++){if(await ev('document.readyState==="complete"&&!!window.HomeYear?.UI'))return;await delay(50);}throw Error('load timeout');}
 async function shot(name){const r=await c.send('Page.captureScreenshot',{format:'png'});await fs.writeFile(path.join(dir,name+'.png'),Buffer.from(r.data,'base64'));}
 async function attach(){await c.send('Page.enable');await c.send('Runtime.enable');await c.send('Network.enable');c.on('Runtime.exceptionThrown',p=>report.errors.push(p));c.on('Runtime.consoleAPICalled',p=>{if(p.type==='error')report.errors.push(p)});c.on('Network.requestWillBeSent',p=>report.requests.push(p.request.url));}
 async function settings(){await close();await click('[data-action=settings]');}
 async function importRaw(raw,valid=false){await settings();await input('[data-testid=save-text]',raw);await click('[data-testid=import]');if(valid)await click('[data-testid=confirm-yes]');}
 async function fresh(seed='QA-FINAL',difficulty='standard'){await close();if(await ev('HomeYear.UI.screen()==="game"'))await click('[data-action=home]');await input('[data-testid=seed]',seed);await input('[data-testid=difficulty]',difficulty);await click('[data-testid=new-game]');if(await ev('!!document.querySelector("[data-testid=confirm-yes]")'))await click('[data-testid=confirm-yes]');if(await ev('!!document.querySelector("[data-action=tour-finish]")'))await click('[data-action=tour-finish]');}
 async function trade(id,mode,q){await close();await click('[data-testid=product-'+id+']');if(mode==='sell')await click('[data-action=trade-mode][data-mode=sell]');await click('[data-action=quantity][data-qty="'+q+'"]');await click('[data-testid=trade-submit]');await close();}
 try{
 edge=await launchEdge();c=edge.cdp;report.browser=edge.version;report.node=process.version;await attach();const t=Date.now();await load();report.performance.push({operation:'cold navigation',ms:Date.now()-t});await shot('start');
 await ck('clean start and disabled continue',()=>ev('HomeYear.UI.screen()==="start"&&document.querySelector("[data-testid=continue]").disabled'));
 await ck('help and four-step tutorial',async()=>{await click('[data-action=help]');await click('[data-action=tutorial]');for(let i=0;i<4;i++){if(!await ev(`document.querySelector('#modal-title').textContent.includes('${i+1} / 4')`))return false;await click('[data-testid=tour-next]');}return ev('!document.querySelector("dialog").open');});
 for(const d of ['easy','standard','challenge'])await ck('new difficulty '+d,async()=>{await fresh('QA-FINAL',d);const s=await snap();return s.difficulty===d&&s.week===1;});
 await ck('seed reproducible initial market',async()=>{await fresh();const a=await snap();await fresh();return JSON.stringify(a.market)===JSON.stringify((await snap()).market);});
 await ck('buy1 buy5 sell1 sell5 exact cash cost',async()=>{const a=await snap(),p=a.market.rice.price;await trade('rice','buy',1);await trade('rice','buy',5);const b=await snap();if(b.inventory.rice.qty!==6||b.inventory.rice.cost!==p+Math.ceil(p/100)+5*p+Math.ceil(5*p/100))return false;await trade('rice','sell',1);await trade('rice','sell',5);const z=await snap();return z.inventory.rice.qty===0&&z.inventory.rice.cost===0&&z.cash===a.cash-2*(Math.ceil(p/100)+Math.ceil(5*p/100));});
 await ck('buy maximum fills capacity and sell all',async()=>{await trade('rice','buy','max');const s=await snap();await click('[data-testid=product-rice]');await input('[data-testid=trade-qty]','100000');const disabled=await ev('document.querySelector("[data-testid=trade-submit]").disabled');await close();await trade('rice','sell','max');return disabled&&s.inventory.rice.qty>0&&(await snap()).inventory.rice.qty===0;});
 await ck('multi-price weighted total cost',async()=>{await trade('rice','buy',1);let a=await snap();await click('[data-testid=next-week]');let b=await snap();await trade('rice','buy',1);let z=await snap();return z.inventory.rice.cost===a.inventory.rice.cost+b.market.rice.price+Math.ceil(b.market.rice.price/100);});
 await ck('input isolation and repeated held key',async()=>{const a=await snap();await input('[data-testid=search]','b');await ev(`document.querySelector('[data-testid=search]').dispatchEvent(new KeyboardEvent('keydown',{key:' ',code:'Space',bubbles:true}));document.body.dispatchEvent(new KeyboardEvent('keydown',{key:' ',code:'Space',repeat:true,bubbles:true}))`);await input('[data-testid=search]','');return (await snap()).week===a.week;});
 await ck('advance actual UI to20',async()=>{while((await snap()).week<20)await click('[data-testid=next-week]');return (await snap()).week===20;});
 const saved=await snap();const baseline=[];for(let i=0;i<3;i++){await click('[data-testid=next-week]');baseline.push(await snap());}
 // Restore the actually obtained week20 through the public import, then manual save.
 await importRaw(JSON.stringify(saved),true);await click('[data-testid=save]');
 await ck('full browser shutdown same profile restart and continue deterministic future',async()=>{
 const profile=edge.profile;await c.send('Browser.close');c.close();await delay(1000);
 restarted=spawn(edge.executable,['--headless=new','--disable-gpu','--no-first-run','--disable-background-networking','--remote-debugging-port=0','--user-data-dir='+profile,'about:blank'],{stdio:'ignore'});
 await delay(1200);let port;for(let i=0;i<100;i++){try{port=Number((await fs.readFile(path.join(profile,'DevToolsActivePort'),'utf8')).split('\n')[0]);const targets=await getJSON('http://127.0.0.1:'+port+'/json/list');c=await CDP.connect(targets.find(x=>x.type==='page').webSocketDebuggerUrl);break;}catch{await delay(100);}}
 await attach();await load();await click('[data-testid=continue]');if(JSON.stringify(await snap())!==JSON.stringify(saved))return false;for(let i=0;i<3;i++){await click('[data-testid=next-week]');if(JSON.stringify(await snap())!==JSON.stringify(baseline[i]))return false;}return true;});
 await ck('invalid JSON missing fields future version atomic rejection',async()=>{const before=await snap(),stored=await ev('localStorage.getItem("homeyear.save.v2")');for(const raw of ['{bad','{}',JSON.stringify({...before,version:999})]){await importRaw(raw);if(JSON.stringify(await snap())!==JSON.stringify(before)||await ev('localStorage.getItem("homeyear.save.v2")')!==stored)return false;}await close();return true;});
 await ck('auto save off and manual save',async()=>{await settings();await click('[data-setting=autoSave]');await close();const raw=await ev('localStorage.getItem("homeyear.save.v2")');await click('[data-testid=next-week]');if(await ev('localStorage.getItem("homeyear.save.v2")')!==raw)return false;await click('[data-testid=save]');return await ev('JSON.parse(localStorage.getItem("homeyear.save.v2")).week===HomeYear.UI.snapshot().week');});
 await ck('storage refusal preserves game and reports failure',async()=>{await settings();await click('[data-setting=autoSave]');await close();await ev('window.oldSet=Storage.prototype.setItem;Storage.prototype.setItem=function(){throw Error("QA quota denied")}');const w=(await snap()).week;await click('[data-testid=next-week]');const ok=(await snap()).week===w+1&&await ev('document.body.textContent.includes("未保存")');await ev('Storage.prototype.setItem=window.oldSet');return ok;});
 await ck('natural no-house complete52 and no53 duplicate',async()=>{while((await snap()).week<52)await click('[data-testid=next-week]');await click('[data-testid=next-week]');await click('[data-testid=confirm-yes]');const a=await snap();await shot('result-no-house');await close();await click('[data-testid=next-week]');return a.week===52&&a.status==='ended'&&!a.house&&JSON.stringify(a)===JSON.stringify(await snap());});
 await fresh('QA-FIXTURE');let fixture=await snap();fixture.cash+=10000000;fixture.stats.grants+=10000000;
 // Only prepare a valid JSON fixture; no engine dispatch/restore is used to exercise UI.
 fixture=await ev(`(()=>{let s=${JSON.stringify(fixture)};HomeYear.record(s);return s})()`);await importRaw(JSON.stringify(fixture),true);
 await ck('five houses four warehouses render and upgrade',async()=>{await click('[data-testid=houses]');if(await ev('document.querySelectorAll("[data-action=buy-house]").length')!==5)return false;await shot('houses');const ids=await ev('HomeYear.houses.map(x=>x.id)');for(const id of ids.slice(0,-1)){await click('[data-testid=house-'+id+']');await click('[data-testid=confirm-yes]');}await close();await click('[data-testid=warehouses]');if(await ev('document.querySelectorAll("[data-action=buy-warehouse]").length')!==4)return false;const ws=await ev('HomeYear.warehouses.slice(1).map(x=>x.id)');for(const id of ws){await click('[data-testid=warehouse-'+id+']');await click('[data-testid=confirm-yes]');}await close();return (await snap()).capacity===120;});
 await ck('fixture owned house week52 trading and settlement',async()=>{while((await snap()).week<52)await click('[data-testid=next-week]');await click('[data-testid=houses]');const lastHouse=await ev('HomeYear.houses.at(-1).id');await click('[data-testid=house-'+lastHouse+']');await click('[data-testid=confirm-yes]');await close();await trade('rice','buy',1);await trade('rice','sell','max');await click('[data-testid=next-week]');await click('[data-testid=confirm-yes]');await shot('result-owned');return (await snap()).status==='ended'&&!!(await snap()).house;});
 await fresh();
 await ck('zero cash and empty holdings reject buy sell',async()=>{let s=await snap();s.stats.expenses+=s.cash;s.cash=0;s=await ev(`(()=>{let s=${JSON.stringify(s)};HomeYear.record(s);return s})()`);await importRaw(JSON.stringify(s),true);await click('[data-testid=product-rice]');let a=await ev('document.querySelector("[data-testid=trade-submit]").disabled');await click('[data-action=trade-mode][data-mode=sell]');let b=await ev('document.querySelector("[data-testid=trade-submit]").disabled');await close();return a&&b&&(await snap()).cash===0;});
 await fresh();
 for(const [w,h,label] of [[1366,768,'1366'],[1600,900,'1600'],[1920,1080,'1920'],[2560,1440,'2560'],[1536,864,'125-equivalent'],[1280,720,'150-equivalent']])await ck('viewport '+label,async()=>{await c.send('Emulation.setDeviceMetricsOverride',{width:w,height:h,deviceScaleFactor:1,mobile:false});await shot('market-'+label);return ev('document.documentElement.scrollWidth<=innerWidth&&document.documentElement.scrollHeight<=innerHeight&&document.querySelector("[data-testid=next-week]").getBoundingClientRect().bottom<=innerHeight');});
 await c.send('Emulation.setDeviceMetricsOverride',{width:1366,height:768,deviceScaleFactor:1,mobile:false});await click('[data-testid=product-rice]');await shot('trade');await close();await settings();await shot('settings');await close();
 await ck('dialog Esc focus return',async()=>{await ev('document.querySelector("[data-testid=houses]").focus()');await click('[data-testid=houses]');await c.send('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});await delay(100);return ev('!document.querySelector("dialog").open&&document.activeElement.dataset.testid==="houses"');});
 await ck('corrupt original preserved until explicit overwrite',async()=>{await ev('localStorage.setItem("homeyear.save.v2","BROKEN ORIGINAL")');await load();await fresh();await click('[data-testid=next-week]');await click('[data-testid=save]');if(await ev('localStorage.getItem("homeyear.save.v2")')!=='BROKEN ORIGINAL')return false;await settings();await click('[data-action=replace]');await click('[data-testid=confirm-yes]');const ok=await ev('JSON.parse(localStorage.getItem("homeyear.save.v2")).week===2');await close();return ok;});
 for(let i=0;i<5;i++){let t=Date.now();await click('[data-testid=next-week]');report.performance.push({operation:'next DOM roundtrip (includes260ms pacing)',ms:Date.now()-t});}
 await ck('no external page requests and no runtime console errors',async()=>!report.errors.length&&!report.requests.some(x=>/^https?:/.test(x)));
 }catch(e){report.fatal=e.stack;console.error(e)}finally{try{if(c){await c.send('Browser.close',{},3000);c.close();}await delay(500);if(restarted)restarted.kill();if(edge)await edge.cleanup();}catch(e){report.cleanup=e.message}report.finished=new Date().toISOString();await fs.writeFile(path.join(dir,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(report.fatal||report.checks.some(x=>!x.pass))process.exitCode=1;}
})();
