'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {H,core,root,dispatch,fixtures}=require('./calendar-event-fixtures.cjs');
const out=process.env.CALENDAR_EVIDENCE_DIR;if(!out)throw Error('Set CALENDAR_EVIDENCE_DIR to an independent output directory');fs.mkdirSync(out,{recursive:true});
const report={kind:'0.7 independent in-memory regression, not simulation/balance evidence',command:process.argv,checks:[],failures:[]};
function test(name,fn){try{fn();report.checks.push(name);}catch(e){report.failures.push({name,error:e.stack});}}
const equal=(a,b)=>assert.equal(JSON.stringify(a),JSON.stringify(b));
const f=fixtures();
test('all 52 seed-derived starts, every 52-week boundary, restore determinism and public projection',()=>{for(const [start,seed]of Object.entries(f.starts)){const a=new H.Engine(seed),b=new H.Engine(seed);assert.equal(a.snapshot().calendarStartWeek,Number(start));assert.equal(a.snapshot().season,H.seasonAt(Number(start)));for(let w=1;w<=52;w++){const s=a.snapshot(),cw=(Number(start)+w-2)%52+1;assert.equal(H.calendarWeek(s),cw);assert.equal(s.season,H.seasonAt(cw));const v=a.visible();assert.equal(v.calendarWeek,cw);assert.equal(v.calendarStartWeek,Number(start));assert.equal(v.season,s.season);for(const key of ['rng','swanLog','activeEvents','macro','onStreak'])assert.equal(key in v,false);equal(s,b.snapshot());if(w===26)b.restore(JSON.parse(JSON.stringify(s)));if(w<52){dispatch(a,'next');dispatch(b,'next');}}assert.equal(a.visible().week,52);assert.equal(a.dispatch({type:'next',revision:a.visible().revision,token:'no53'}).ok,false);}});
test('calendar derivation consumes none of four original RNG streams',()=>{for(const seed of Object.values(f.starts)){const s=H.create(seed);assert.equal(s.rng.market,H.seed(seed+':market'));assert.equal(s.rng.events,H.seed(seed+':events'));assert.equal(s.rng.visual,H.seed(seed+':visual'));const copy=H.clone(s);copy.rng.listing=H.seed(seed+':listing');equal(H.initialListing(copy),s.listing);assert.equal(copy.rng.listing,s.rng.listing);const rng=JSON.stringify(s.rng);H.calendarWeek(s);H.calendarStart(seed);H.seasonAt(H.calendarWeek(s));assert.equal(JSON.stringify(s.rng),rng);}});
test('price cosine uses calendar week including wrap',()=>{const C=core();C.random=()=>.5;for(const seed of Object.values(f.starts)){const s=C.create(seed);s.week=2;s.activeEvents=[];for(const p of C.products){s.market[p.id].trend=0;}const before=C.clone(s);C.prices(s);for(const p of C.products){const center=p.base*(1+p.season*Math.cos((C.calendarWeek(before)-1)/52*Math.PI*2+p.phase));const expected=Math.max(p.min,Math.min(p.max,p.base+Math.round(.15*(center-p.base))));assert.equal(s.market[p.id].price,expected);}}});
test('strict safe calendar start/seed/season/unknown fields; restore atomic rejection',()=>{const e=new H.Engine('strict-calendar'),good=e.snapshot();for(const mutate of [s=>delete s.calendarStartWeek,s=>s.calendarStartWeek=0,s=>s.calendarStartWeek=53,s=>s.calendarStartWeek=1.5,s=>s.calendarStartWeek=NaN,s=>s.calendarStartWeek='2',s=>s.calendarStartWeek=s.calendarStartWeek%52+1,s=>s.calendarWeek=1,s=>s.season=s.season==='冬'?'夏':'冬',s=>s.extra=true,s=>s.stats.fees++]){const bad=H.clone(good);mutate(bad);assert.throws(()=>e.restore(bad));equal(e.snapshot(),good);}});
test('summer heat scheduling and log validation use same calendar',()=>{const heat=f.events.swan_heat.after;assert.equal(H.seasonAt(H.calendarWeek(heat)), '夏');assert.equal(heat.season,'夏');H.validate(heat);const bad=H.clone(heat);const row=bad.swanLog.find(l=>l.id==='swan_heat');row.week=4;assert.throws(()=>H.validate(bad));for(const seed of Object.values(f.starts)){const e=new H.Engine(seed);for(let w=2;w<=52;w++){dispatch(e,'next');const s=e.snapshot();for(const l of s.swanLog.filter(l=>l.id==='swan_heat'))assert.equal(H.seasonAt(H.calendarWeek(s,l.week)),'夏');}}});
test('current save6 read/write/export/import, old1/2/3/4/5 rejected without writes, old storage preserved',()=>{const map=new Map(),store={getItem:k=>map.has(k)?map.get(k):null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)},saves=new H.SaveAdapter(store),e=new H.Engine('save6');assert.equal(saves.key,'homeyear.save.v11');for(let n=1;n<=10;n++)map.set('homeyear.save.v'+n,'original-v'+n);assert.equal(saves.load().notice,H.oldSaveNotice);assert.equal(saves.isQuarantined(),false);assert.equal(saves.save(e.snapshot()).ok,true);equal(saves.load().state,e.snapshot());const imported=new H.Engine();assert.equal(saves.import(saves.export(e.snapshot()),imported).ok,true);equal(imported.snapshot(),e.snapshot());for(let n=1;n<=10;n++){const old=H.clone(e.snapshot());old.version=n;delete old.calendarStartWeek;const before=JSON.stringify([...map]);assert.equal(saves.import(JSON.stringify(old),e).ok,false);assert.equal(saves.stageOld(JSON.stringify(old)).ok,false);assert.equal(saves.migrate(JSON.stringify(old)).ok,false);assert.equal(JSON.stringify([...map]),before);assert.equal(map.get('homeyear.save.v'+n),'original-v'+n);}map.set(saves.key,'BROKEN-V6');assert.equal(saves.load().ok,false);assert.equal(saves.damaged(),'BROKEN-V6');assert.equal(saves.save(e.snapshot()).ok,false);assert.equal(map.get(saves.key),'BROKEN-V6');assert.equal(saves.save(e.snapshot(),{replaceDamaged:true}).ok,true);assert.equal(saves.remove().ok,true);assert.equal(saves.load().state,null);});
test('save failure is post-commit and exports remain usable',()=>{const e=new H.Engine('denied'),saves=new H.SaveAdapter({getItem:()=>null,setItem:()=>{throw Error('quota');},removeItem:()=>{}});e.onCommit=s=>{const r=saves.save(s);if(!r.ok)throw Error(r.error);};const r=dispatch(e,'next');assert.equal(r.saveError,'quota');assert.equal(e.visible().week,2);assert.equal(JSON.parse(saves.export(e.snapshot())).version,11);});
test('all current swan fixtures retain strict logs, real signed changes and complete static sources',()=>{let pos=false,neg=false;assert.equal(Object.keys(f.events).length,H.events.filter(e=>e.tier==='swan').length);for(const [id,pair]of Object.entries(f.events)){H.validate(pair.before);H.validate(pair.after);const e=new H.Engine();e.restore(pair.before);dispatch(e,'next');equal(e.snapshot(),pair.after);const ev=H.events.find(e=>e.id===id),o=H.swanOrigins[id];for(const field of ['name','date','agency','title','url','facts','adaptation','kind'])assert.equal(typeof o[field],'string');if(o.kind==='verified')assert.match(o.url,/^https:\/\//);else{assert.equal(o.kind,'original');assert.equal(o.url,'');assert.match(o.adaptation,/强行对应/);}for(const product of Object.keys(ev.effects)){const bps=H.changeBps(pair.after.market[product]);pos=pos||bps>0;neg=neg||bps<0;}assert(pair.after.swanLog.some(l=>l.id===id&&l.week===pair.after.week));}assert(pos&&neg);assert.match(H.swanOrigins.swan_efficiency.adaptation,/股票跌幅不等于显卡零售价/);assert.match(H.swanOrigins.swan_egg_relief.facts,/不是产能已恢复/);assert.equal(H.swanOrigins.swan_recall.kind,'verified');assert.equal(H.swanOrigins.swan_recall.url,'https://www.cpsc.gov/Recalls/2016/Samsung-Recalls-Galaxy-Note7-Smartphones');assert.equal(H.swanOrigins.swan_blackout.kind,'verified');assert.equal(H.swanOrigins.swan_blackout.url,'https://blog.cloudflare.com/october-2021-facebook-outage/');for(const id of ['swan_avocado','swan_salmonrice','swan_film','swan_blindbox'])assert.match(H.swanOrigins[id].adaptation,/相近假名/);assert.equal(H.events.filter(e=>e.tier==='swan'&&H.swanOrigins[e.id].kind==='original').length,28);assert.equal(H.events.filter(e=>e.tier==='swan'&&H.swanOrigins[e.id].kind==='verified').length,17);});
report.summary={passed:report.checks.length,failed:report.failures.length};fs.writeFileSync(path.join(out,'fixtures.json'),JSON.stringify(f,null,2));fs.writeFileSync(path.join(out,'core-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(report.failures.length)process.exitCode=1;
