'use strict';
// Targeted P2 regression. Records old failure using the archived pre-fix source,
// then checks supported-old precedence without changing current v4 isolation.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {pathToFileURL}=require('node:url'),{launchEdge,delay}=require('./cdp-helper.cjs');
const root=path.resolve(__dirname,'..'),out=path.resolve(process.env.UI_EVIDENCE_DIR||path.join(root,'docs/black-swan-evidence/phase-b-20261004/review-fixes-v1/targeted'));
const beforePath=path.join(root,'docs/black-swan-evidence/phase-b-20261004/review-fixes-v1/save-before.js');
const raw2=fs.readFileSync(path.join(root,'docs/fixtures/v2-baseline-migrate.json'),'utf8'),raw1=' V1-ORIGINAL \n';
function core(before=false){const c=vm.createContext({console});c.window=c;for(const f of ['data','math','v2-baseline','v3-baseline','market','trading','statistics','validation','game','save'])vm.runInContext(fs.readFileSync(before&&f==='save'?beforePath:path.join(root,'js/'+f+'.js'),'utf8'),c);return c.HomeYear;}
function memory(entries,read){const map=new Map(entries);return {map,getItem(k){if(read)return read(k,map);return map.has(k)?map.get(k):null;},setItem(k,v){map.set(k,v);},removeItem(k){map.delete(k);}};}
const H=core(),old=core(true),raw3='\n '+JSON.stringify(H.v3.create('REVIEW-V1'),null,2)+'\n';
const report={kind:'targeted Node + real Edge file://; P2/P3 repair evidence',nodeChecks:[],browserChecks:[],errors:[],external:[],beforeSaveSha256:crypto.createHash('sha256').update(fs.readFileSync(beforePath)).digest('hex')};
function test(name,f){f();report.nodeChecks.push({name,pass:true});}
(async()=>{let edge;fs.mkdirSync(out,{recursive:true});try{
  for(const [name,entries] of [['v3+v2+v1',[['homeyear.save.v3',raw3],['homeyear.save.v2',raw2],['homeyear.save.v1',raw1]]],['v2+v1',[['homeyear.save.v2',raw2],['homeyear.save.v1',raw1]]]]){
    const st=memory(entries),ad=new old.SaveAdapter(st),prior=new Map(st.map),r=ad.load();assert.equal(r.ok,false);assert.equal(ad.isQuarantined(),true);assert.equal(r.raw,null);assert.deepEqual(st.map,prior);
    report.withdrawnBefore=report.withdrawnBefore||[];report.withdrawnBefore.push({name,load:JSON.parse(JSON.stringify(r)),quarantine:ad.isQuarantined(),damaged:ad.damaged(),unchanged:true});
    test(name+' supported-old priority, no quarantine or writes',()=>{const st=memory(entries),ad=new H.SaveAdapter(st),before=new Map(st.map),r=ad.load();assert.equal(r.ok,true,r.error);assert.equal(r.state,null);assert.equal(ad.isQuarantined(),false);assert.equal(ad.damaged(),null);assert.equal(name.startsWith('v3')?r.oldV3.ok:r.legacy.ok,true);assert.deepEqual(st.map,before);const m=ad.migrate(name.startsWith('v3')?raw3:raw2);assert.equal(m.ok,true,m.error);for(const [k,v]of entries)assert.equal(st.map.get(k),v);assert.equal(ad.parse(st.map.get('homeyear.save.v4')).ok,true);});
  }
  test('bad v3 + valid v2 + v1 recognized v2, explicit migration',()=>{const st=memory([['homeyear.save.v3','BAD'],['homeyear.save.v2',raw2],['homeyear.save.v1',raw1]]),ad=new H.SaveAdapter(st),r=ad.load();assert.equal(r.ok,true);assert.equal(r.oldV3.ok,false);assert.equal(r.legacy.ok,true);assert.equal(ad.isQuarantined(),false);assert.equal(ad.migrate(raw2).ok,true);assert.equal(st.map.get('homeyear.save.v3'),'BAD');assert.equal(st.map.get('homeyear.save.v1'),raw1);});
  for(const bad of ['BAD',JSON.stringify({version:999})])test('unrecognized old formats + v1 remain rejected '+bad,()=>{const st=memory([['homeyear.save.v3',bad],['homeyear.save.v2',bad],['homeyear.save.v1',raw1]]),before=new Map(st.map),ad=new H.SaveAdapter(st),r=ad.load();assert.equal(r.ok,false);assert.equal(r.oldV3.ok,false);assert.equal(r.legacy.ok,false);assert.equal(ad.isQuarantined(),true);assert.equal(ad.migrate(bad).ok,false);assert.deepEqual(st.map,before);});
  for(const current of ['BROKEN',JSON.stringify({...H.create('future'),version:999})])test('bad/future current v4 never falls back '+current.slice(0,12),()=>{const st=memory([['homeyear.save.v4',current],['homeyear.save.v3',raw3],['homeyear.save.v2',raw2],['homeyear.save.v1',raw1]]),ad=new H.SaveAdapter(st),before=new Map(st.map),r=ad.load();assert.equal(r.ok,false);assert.equal(r.raw,current);assert.equal(ad.isQuarantined(),true);assert.equal(ad.migrate(raw3).ok,false);assert.deepEqual(st.map,before);});
  test('supported old does not consult throwing v1 getter; unrecognized reads fail strictly',()=>{for(const entries of [[['homeyear.save.v3',raw3]],[['homeyear.save.v2',raw2]]]){let reads=0;const st=memory(entries,(k,m)=>{if(k==='homeyear.save.v1'){reads++;throw Error('v1 denied');}return m.has(k)?m.get(k):null;}),r=new H.SaveAdapter(st).load();assert.equal(r.ok,true);assert.equal(reads,0);}const st=memory([],()=>{throw Error('read denied');}),ad=new H.SaveAdapter(st);assert.equal(ad.load().ok,false);assert.equal(ad.isQuarantined(),true);});
  test('v1 read failure without recognized supported old remains structured rejection',()=>{const st=memory([],(k)=>{if(k==='homeyear.save.v1')throw Error('v1 denied');return null;}),r=new H.SaveAdapter(st).load();assert.equal(r.ok,false);assert.match(r.error,/v1 denied/);});
  edge=await launchEdge();const c=edge.cdp,ev=x=>c.evaluate(x);report.browser=edge.version.Browser;await c.send('Page.enable');await c.send('Runtime.enable');await c.send('Network.enable');await c.send('Emulation.setDeviceMetricsOverride',{width:1366,height:768,deviceScaleFactor:1,mobile:false});
  c.on('Runtime.exceptionThrown',p=>report.errors.push(p.exceptionDetails));c.on('Network.requestWillBeSent',p=>{if(/^https?:|^wss?:/.test(p.request.url))report.external.push(p.request.url);});
  function check(name,pass,detail){report.browserChecks.push({name,pass:!!pass,detail});assert.ok(pass,name);}
  const wait=async()=>{for(let i=0;i<120;i++){try{if(await ev('document.readyState==="complete"&&!!HomeYear.UI&&!!document.querySelector("[data-testid=new-game]")'))return;}catch{}await delay(80);}throw Error('ready timeout');};
  const reload=async()=>{await c.send('Page.reload');await wait();};const click=async sel=>{await ev(`(()=>{const el=document.querySelector(${JSON.stringify(sel)});if(!el||el.disabled)throw Error('missing '+${JSON.stringify(sel)});el.click()})()`);await delay(200);};
  const snapshotStorage=()=>ev('JSON.stringify(Object.fromEntries(Object.keys(localStorage).sort().map(k=>[k,localStorage.getItem(k)])))');
  await c.send('Page.navigate',{url:pathToFileURL(path.join(root,'index.html')).href});await wait();
  for(const [name,v3,selector]of [['v3+v2+v1',raw3,'[data-testid=migrate]'],['v2+v1',null,'[data-testid=migrate]'],['bad-v3+v2+v1','BAD','[data-testid=migrate-v2]']]){
    await ev(`localStorage.clear();localStorage.setItem('homeyear.tutorial','seen');localStorage.setItem('homeyear.save.v1',${JSON.stringify(raw1)});localStorage.setItem('homeyear.save.v2',${JSON.stringify(raw2)});${v3!==null?`localStorage.setItem('homeyear.save.v3',${JSON.stringify(v3)});`:''}`);await reload();
    const initial=await ev(`(()=>{const ad=new HomeYear.SaveAdapter(),r=ad.load();return {ok:r.ok,state:r.state,oldV3:r.oldV3&&r.oldV3.ok,legacy:r.legacy&&r.legacy.ok,quarantine:ad.isQuarantined(),text:document.body.innerText}})()`);check(name+' load recognized supported old, state null',initial.ok&&initial.state===null&&!initial.quarantine&&initial.legacy&&(name!=='v3+v2+v1'||initial.oldV3),initial);check(name+' UI no false isolation',!/已隔离|替换损坏|不支持自动迁移/.test(initial.text));
    const before=await snapshotStorage();await click(selector);check(name+' initial single explicit confirmation',await ev('!!document.querySelector("[data-testid=confirm-yes]")&&!document.querySelector(".dialog-body").innerText.includes("替换损坏")'));await ev(`[...document.querySelectorAll('dialog button')].find(e=>e.textContent==='取消').click()`);await delay(80);check(name+' cancel zero writes',before===await snapshotStorage());
    await click(selector);await click('[data-testid=confirm-yes]');check(name+' one confirm finishes migration, no replacement dialog',await ev('HomeYear.UI.screen()==="game"&&HomeYear.UI.snapshot().version===4&&!document.querySelector("dialog").open'));
    check(name+' all v1/v2/v3 raw originals unchanged',await ev(`localStorage.getItem('homeyear.save.v1')===${JSON.stringify(raw1)}&&localStorage.getItem('homeyear.save.v2')===${JSON.stringify(raw2)}&&localStorage.getItem('homeyear.save.v3')===${JSON.stringify(v3)}`));check(name+' new v4 parses and current snapshot persisted',await ev('new HomeYear.SaveAdapter().parse(localStorage.getItem("homeyear.save.v4")).ok&&JSON.stringify(HomeYear.UI.snapshot())===localStorage.getItem("homeyear.save.v4")'));
    const shot=await c.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(path.join(out,name+'-migrated.png'),Buffer.from(shot.data,'base64'));
  }
  await ev(`localStorage.clear();localStorage.setItem('homeyear.save.v1',${JSON.stringify(raw1)});localStorage.setItem('homeyear.save.v3','BAD');localStorage.setItem('homeyear.save.v2','BAD')`);await reload();check('unrecognized old + v1 browser rejects, no supported default entry',await ev('(()=>{const r=new HomeYear.SaveAdapter().load();return !r.ok&&!r.oldV3.ok&&!r.legacy.ok&&!document.querySelector("[data-testid=migrate],[data-testid=migrate-v2]")})()'));
  await ev(`localStorage.setItem('homeyear.save.v4','BROKEN');localStorage.setItem('homeyear.save.v3',${JSON.stringify(raw3)});localStorage.setItem('homeyear.save.v2',${JSON.stringify(raw2)})`);await reload();const before=await snapshotStorage();await click('[data-testid=migrate]');await click('[data-testid=confirm-yes]');check('actual bad v4 retains second replacement confirmation',await ev('document.querySelector(".dialog-body").innerText.includes("替换损坏的 v4")'));await ev(`[...document.querySelectorAll('dialog button')].find(e=>e.textContent==='取消').click()`);check('actual bad v4 second cancellation zero writes',before===await snapshotStorage());
  check('browser current-key read exception is structured, no write/fallback',await ev(`(()=>{const get=Storage.prototype.getItem,before=JSON.stringify(Object.fromEntries(Object.keys(localStorage).map(k=>[k,get.call(localStorage,k)])));try{Storage.prototype.getItem=function(k){if(k==='homeyear.save.v4')throw new DOMException('current read denied','SecurityError');return get.call(this,k);};const ad=new HomeYear.SaveAdapter(),r=ad.load();return !r.ok&&ad.isQuarantined()&&r.error.includes('current read denied')&&before===JSON.stringify(Object.fromEntries(Object.keys(localStorage).map(k=>[k,get.call(localStorage,k)])));}finally{Storage.prototype.getItem=get;}})()`));
  check('browser real localStorage getter exception is caught',await ev(`(()=>{const descriptor=Object.getOwnPropertyDescriptor(window,'localStorage');let calls=0;try{Object.defineProperty(window,'localStorage',{configurable:true,get(){calls++;throw new DOMException('getter denied','SecurityError');}});const ad=new HomeYear.SaveAdapter(),r=ad.load();return !r.ok&&ad.isQuarantined()&&r.error.includes('getter denied')&&calls>0;}finally{Object.defineProperty(window,'localStorage',descriptor);}})()`));
  check('no runtime errors/external requests',report.errors.length===0&&report.external.length===0);
}catch(e){report.failure=e.stack;console.error(e);process.exitCode=1;}finally{fs.writeFileSync(path.join(out,'targeted-report.json'),JSON.stringify(report,null,2));if(edge)await edge.cleanup();console.log(report.nodeChecks.length+' Node checks, '+report.browserChecks.length+' browser checks'+(report.failure?' FAILED':' passed'));}})();
