'use strict';
// Fixed mechanism regressions only; no strategy or economic-balance conclusions.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {H,core,dispatch}=require('./calendar-event-fixtures.cjs');
const out=process.env.RUMOR_EVIDENCE_DIR;if(!out)throw Error('Explicit RUMOR_EVIDENCE_DIR required');fs.mkdirSync(out,{recursive:true});
const report={kind:'0.7 fixed mechanism regression; not economic balance or observed accuracy',checks:[],failures:[],samples:[],shocks:[]};
const equal=(a,b)=>assert.equal(JSON.stringify(a),JSON.stringify(b));
function test(name,f){try{f();report.checks.push(name);}catch(e){report.failures.push({name,error:e.stack});}}
const expected={swan_route:{phone:18000,gpu:12000,ac:10000},swan_efficiency:{gpu:-7000,phone:-4500},swan_egg_short:{eggs:20000,rice:5000},swan_heat:{ac:22000,fruit:7000,umbrella:-4500},swan_tariff:{phone:15000,watch:-6500,collectible:-7000},swan_protection:{mask:40000,rice:8000,eggs:6000},swan_egg_relief:{eggs:-7000,rice:-3500},swan_export:{gpu:16000,phone:8000},swan_redsea:{phone:10000,watch:8000},swan_gas:{coat:16000},swan_nino:{fruit:9000,rice:5000},swan_grain:{rice:-7000,pork:-3500},swan_meat:{pork:16000},swan_rates:{watch:-8000,collectible:-9000},swan_bank:{collectible:-9500,gpu:-5000}};
test('fifteen exact signed first hits, alias maxima, noise-free normal and clipped prices',()=>{
 const C=core(),original=C.random;C.random=()=>.5;
 try{for(const [id,effects]of Object.entries(expected)){const ev=C.events.find(e=>e.id===id);equal(Object.fromEntries(Object.entries(ev.effects).map(([p,f])=>[p,f.bps])),effects);
  for(const mode of ['base','upper','lower']){const s=C.create('shock-'+id);s.week=4;s.activeEvents=[{id,started:4,until:4+ev.duration-1}];
   for(const p of C.products){s.market[p.id].price=mode==='upper'?p.max:mode==='lower'?p.min:p.base;s.market[p.id].trend=0;}
   const before=C.clone(s);C.prices(s);for(const [pid,bps]of Object.entries(effects)){const p=C.product(pid),prev=before.market[pid].price,raw=prev+Math.round(prev*bps/10000),price=Math.max(p.min,Math.min(p.max,raw));assert.equal(s.market[pid].price,price);report.shocks.push({id,productId:pid,mode,previous:prev,raw,price,changeBps:C.changeBps(s.market[pid]),clipped:raw!==price});}
  }
 }
 const maxima={rice:100000,eggs:100000,fruit:100000,phone:1000000,gpu:800000,ac:800000,mask:200000};for(const [id,max]of Object.entries(maxima)){assert.equal(C.product(id).max,max);assert.equal(C.product(id).maxPrice,max);}for(const e of C.events)for(const f of Object.values(e.effects||{}))assert(f.bps>-10000);assert.equal(C.swanRules.probability,.42);assert.equal(C.swanRules.firstWeek,4);assert.equal(C.swanRules.lastWeek,50);assert.equal(C.swanRules.gap,4);assert.equal(C.swanRules.limit,8);
 }finally{C.random=original;}
});
test('persistent first hit never repeats; capped center and unchanged 15 percent reversion',()=>{const C=core();C.random=()=>.5;equal(C.persistCap,{daily:3000,industry:6000,spec:8000});for(const id of ['swan_route','swan_heat','swan_tariff']){const ev=C.events.find(e=>e.id===id),s=C.create('persist-'+id);s.week=4;s.activeEvents=[{id,started:4,until:4+ev.duration-1}];for(const p of C.products)s.market[p.id].trend=0;C.prices(s);s.week=5;const before=C.clone(s),diag=C.prices(s);assert.equal(diag.startedProducts.length,0);for(const [pid,fx]of Object.entries(ev.effects)){const p=C.product(pid),m=before.market[pid],persist=fx.kind==='persist'?Math.max(-C.persistCap[p.role],Math.min(C.persistCap[p.role],fx.bps)):0,seasonal=1+p.season*Math.cos((C.calendarWeek(s)-1)/52*Math.PI*2+p.phase),center=p.base*seasonal*s.macro*(1+persist/10000),want=Math.max(p.min,Math.min(p.max,m.price+Math.round(.15*(center-m.price))));assert.equal(s.market[pid].price,want);}}});
test('clone preview equals real next market and all four RNG, including personal draws; no source mutation',()=>{let personal=0;for(let n=0;n<12;n++){const e=new H.Engine('MECHANISM-'+n);for(let w=1;w<52;w++){const s=e.snapshot(),before=JSON.stringify(s),preview=H.previewMarket(s);equal(s,JSON.parse(before));dispatch(e,'next');const actual=e.snapshot();for(const key of ['week','season','macro','listing','absence','onStreak','market','legacy','activeEvents','swanLog','rng','personal','personalEvent'])equal(preview[key],actual[key]);if(actual.personalEvent)personal++;}}assert(personal>0);report.personalDraws=personal;});
test('preview invokes shared step without validation/dispatch/rumor recursion or personal accounting',()=>{const C=core(),s=C.create('PURE-PREVIEW'),before=JSON.stringify(s);C.validate=()=>{throw Error('recursive validation');};C.makeRumors=()=>{throw Error('recursive rumor');};C.personal=()=>{throw Error('accounting in preview');};C.news=()=>{throw Error('news in preview');};C.record=()=>{throw Error('record in preview');};C.Engine=()=>{throw Error('engine in preview');};const p=C.previewMarket(s);assert.equal(p.week,2);equal(s,JSON.parse(before));});
test('fixed hint samples include correct, wrong, empty and off-sale target; final clipped threshold, three public fields',()=>{let correct=0,wrong=0,empty=0,offSale=0;for(let n=0;n<20;n++){const e=new H.Engine('HINT-SAMPLE-'+n);for(let w=1;w<52;w++){const s=e.snapshot(),rng=JSON.stringify(s.rng),p=H.previewMarket(s),candidates=s.listing.filter(id=>Math.abs(H.changeBps(p.market[id]))>=1000),rumors=H.makeRumors(s);equal(rumors,s.rumors);assert.equal(JSON.stringify(s.rng),rng);assert.equal(rumors.length,Math.min(2,candidates.length));if(!rumors.length)empty++;for(const r of rumors){equal(Object.keys(r),['productId','direction','sourceId']);assert(s.listing.includes(r.productId));assert(candidates.includes(r.productId));const truth=H.changeBps(p.market[r.productId])>0?'up':'down',right=r.direction===truth;right?correct++:wrong++;if(!p.listing.includes(r.productId))offSale++;if(report.samples.length<12)report.samples.push({seed:s.seed,week:w,rumor:r,finalChangeBps:H.changeBps(p.market[r.productId]),targetListed:p.listing.includes(r.productId),matches:right});}dispatch(e,'next');}assert.equal(e.snapshot().rumors.length,0);}assert(correct>0&&wrong>0&&empty>0&&offSale>0);report.coverage={correct,wrong,empty,offSale,note:'fixed regression sample counts, not accuracy or balance evidence'};});
test('cash, holdings, revision do not select hints; same-week buy/sell/warehouse/house/read/save never redraw',()=>{const e=new H.Engine('STABLE-HINT'),s=e.snapshot(),r=H.clone(s.rumors);for(const change of [x=>x.cash+=1,x=>x.inventory.rice.qty=2,x=>x.revision+=20]){const changed=H.clone(s);change(changed);equal(H.makeRumors(changed),r);}s.cash+=2000000;s.stats.grants+=2000000;H.record(s);e.restore(s);const id=s.listing.find(id=>H.product(id).size<=2);for(const [type,pid,q]of [['buy',id,2],['sell',id,1],['warehouse','small'],['house','studio']]){dispatch(e,type,pid,q);equal(e.snapshot().rumors,r);}const store=new Map(),a=new H.SaveAdapter({getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)});for(let n=0;n<5;n++){e.visible();e.snapshot();e.diagnostics();assert(a.save(e.snapshot()).ok);equal(a.load().state.rumors,r);}const other=new H.Engine('RESTORE');assert(a.import(a.export(e.snapshot()),other).ok);equal(other.snapshot(),e.snapshot());while(e.visible().week<52){dispatch(e,'next');dispatch(other,'next');equal(e.snapshot(),other.snapshot());}equal(e.visible().rumors,[]);dispatch(e,'end');equal(e.snapshot().rumors,[]);});
test('strict rumor missing/extra keys, list/count/duplicates/enums/source, wrong direction and target52 atomic rejection',()=>{const e=new H.Engine('STRICT-HINT');while(!e.snapshot().rumors.length&&e.visible().week<51)dispatch(e,'next');const good=e.snapshot();assert(good.rumors.length);const mutations=[s=>delete s.rumors,s=>s.rumors=null,s=>s.rumors.push(s.rumors[0],s.rumors[0]),s=>s.rumors=[s.rumors[0],s.rumors[0]],s=>delete s.rumors[0].sourceId,s=>s.rumors[0].futureBps=123,s=>s.rumors[0].direction='flat',s=>s.rumors[0].sourceId='reliable',s=>s.rumors[0].productId=H.products.find(p=>!s.listing.includes(p.id)).id,s=>s.rumors[0].direction=s.rumors[0].direction==='up'?'down':'up',s=>s.rumors=[]];for(const mutate of mutations){const bad=H.clone(good);mutate(bad);assert.throws(()=>e.restore(bad));equal(e.snapshot(),good);}while(e.visible().week<51)dispatch(e,'next');equal(H.makeRumors(e.snapshot()),e.snapshot().rumors);dispatch(e,'next');const bad=e.snapshot();bad.rumors=[good.rumors[0]];assert.throws(()=>e.restore(bad));dispatch(e,'end');assert.equal(e.snapshot().rumors.length,0);});
test('future/current damaged save6 quarantine and SecurityError/Quota post-commit, old v5 raw retained',()=>{const map=new Map(),store={getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)},a=new H.SaveAdapter(store),e=new H.Engine('SAVE6');map.set('homeyear.save.v5','old-original');assert.equal(a.load().notice,H.oldSaveNotice);assert.equal(a.oldRaw(),'old-original');assert(a.save(e.snapshot()).ok);assert.equal(map.get('homeyear.save.v5'),'old-original');for(const makeRaw of [()=>'{',()=> 'null',()=>{const s=e.snapshot();delete s.rumors;return JSON.stringify(s);},()=>{const s=e.snapshot();s.rumors=[{productId:s.listing[0],direction:'flat',sourceId:'street'}];return JSON.stringify(s);}]){const original=makeRaw();map.set(a.key,original);assert(!a.load().ok);assert.equal(a.damaged(),original);assert(!a.save(e.snapshot()).ok);assert.equal(map.get(a.key),original);assert.equal(map.get('homeyear.save.v5'),'old-original');assert(a.save(e.snapshot(),{replaceDamaged:true}).ok);}const bad=e.snapshot();bad.version=9;const raw=JSON.stringify(bad);map.set(a.key,raw);assert(!a.load().ok);assert.equal(a.damaged(),raw);assert(!a.save(e.snapshot()).ok);assert.equal(map.get(a.key),raw);assert(a.save(e.snapshot(),{replaceDamaged:true}).ok);for(const name of ['SecurityError','QuotaExceededError']){const denied=new H.SaveAdapter({getItem:()=>{throw Object.assign(Error(name),{name});},setItem:()=>{throw Object.assign(Error(name),{name});},removeItem:()=>{throw Object.assign(Error(name),{name});}});assert(!denied.load().ok);e.onCommit=s=>{const r=denied.save(s);if(!r.ok)throw Error(r.error);};const before=e.visible().week,r=dispatch(e,'next');assert(r.saveError);assert.equal(e.visible().week,before+1);assert.equal(JSON.parse(denied.export(e.snapshot())).version,8);}});
report.summary={passed:report.checks.length,failed:report.failures.length};fs.writeFileSync(path.join(out,'mechanism-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({summary:report.summary,failures:report.failures,coverage:report.coverage,personalDraws:report.personalDraws},null,2));if(report.failures.length)process.exitCode=1;
