'use strict';
// Rules 0.7 current warehouse regression. Adapted from historical Phase A tests.
// Fixtures are current public Engine snapshots/imports,
// not balance evidence or manual play. No production state-mutation test hooks.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),cp=require('node:child_process');
const {pathToFileURL}=require('node:url'),{launchEdge,delay}=require('./cdp-helper.cjs');
const root=path.resolve(__dirname,'..'),out=path.resolve(process.env.UI_EVIDENCE_DIR||(()=>{throw Error('Explicit independent UI_EVIDENCE_DIR required')})());
const report={kind:'Automated Edge file://; not manual play',checks:[],layouts:[],errors:[],external:[],shots:[],rules:'0.7', provenance:'Adapted current-only warehouse tests; historical migration suite remains unchanged'};
const {H}=require('./calendar-event-fixtures.cjs');
const check=(name,pass,detail)=>{report.checks.push({name,pass:!!pass,detail});if(!pass)console.error('FAIL',name,detail);};
function dispatch(e,type,id,qty){const r=e.dispatch({type,id,qty,revision:e.visible().revision,token:'fixture-'+(++dispatch.seq)});if(!r.ok)throw Error(r.error);}dispatch.seq=0;
function holdingFixture(qty=11){const e=new H.Engine('UI-A-HOLD');let s=e.snapshot();s.cash+=10000000;s.stats.grants+=10000000;H.record(s);e.restore(s);dispatch(e,'warehouse','large');const id=e.snapshot().listing.filter(id=>H.holding(id).size<=2).sort((a,b)=>e.snapshot().market[a].price-e.snapshot().market[b].price)[0];dispatch(e,'buy',id,1);dispatch(e,'next');while(!e.snapshot().listing.includes(id))dispatch(e,'next');if(qty>1)dispatch(e,'buy',id,qty-1);return {s:e.snapshot(),id};}
// All twelve current products acquired through actual buys and rotations; no old migration.
function multiHolding(){const e=new H.Engine('WAREHOUSE-CURRENT-12');let s=e.snapshot();s.cash+=100000000;s.stats.grants+=100000000;H.record(s);e.restore(s);dispatch(e,'warehouse','large');for(let w=1;w<20;w++){s=e.snapshot();for(const id of s.listing)if(!s.inventory[id].qty)dispatch(e,'buy',id,id==='rice'?9:3);if(Object.values(e.snapshot().inventory).every(i=>i.qty))return e.snapshot();dispatch(e,'next');}throw Error('12 holdings not reached');}
const multi=multiHolding();
(async()=>{let edge,c;fs.mkdirSync(out,{recursive:true});try{edge=await launchEdge();c=edge.cdp;report.browser=edge.version.Browser;const ev=x=>c.evaluate(x),snap=()=>ev('HomeYear.UI.snapshot()');
await c.send('Page.enable');await c.send('Emulation.setFocusEmulationEnabled',{enabled:true});await c.send('Runtime.enable');await c.send('Network.enable');c.on('Runtime.exceptionThrown',p=>report.errors.push(p.exceptionDetails));c.on('Network.requestWillBeSent',p=>{if(/^https?:|^wss?:/.test(p.request.url))report.external.push(p.request.url);});
const click=async sel=>{await ev(`(()=>{const e=document.querySelector(${JSON.stringify(sel)});if(!e||e.disabled)throw Error('missing/disabled '+${JSON.stringify(sel)});e.click()})()`);await delay(250);if(sel==='[data-testid=next-week]'&&await ev("document.querySelector('dialog').open&&document.querySelector('dialog').dataset.kind==='major-event'")){await ev("document.querySelector('dialog [data-action=close]').click()");await delay(30);}};
const input=async(sel,v)=>ev(`(()=>{const e=document.querySelector(${JSON.stringify(sel)});e.value=${JSON.stringify(v)};e.dispatchEvent(new Event('input',{bubbles:true}));})()`);
const close=async()=>{if(await ev('document.querySelector("dialog").open'))await click('[data-action=close]');};
const importState=async s=>{await close();await click('[data-action=settings]');await input('[data-testid=save-text]',JSON.stringify(s));await click('[data-testid=import]');await click('[data-testid=confirm-yes]');check('import complete snapshot',JSON.stringify(await snap())===JSON.stringify(s));};
const shot=async name=>{const r=await c.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});fs.writeFileSync(path.join(out,name+'.png'),Buffer.from(r.data,'base64'));report.shots.push(name+'.png');};
const press=async(key,code,vk,repeats=0)=>{await c.send('Input.dispatchKeyEvent',{type:'keyDown',key,code,windowsVirtualKeyCode:vk,text:key==='Enter'?'\r':key});for(let i=0;i<repeats;i++){await delay(260);await c.send('Input.dispatchKeyEvent',{type:'keyDown',key,code,windowsVirtualKeyCode:vk,text:key==='Enter'?'\r':key,autoRepeat:true});}await c.send('Input.dispatchKeyEvent',{type:'keyUp',key,code,windowsVirtualKeyCode:vk});await delay(260);};
await c.send('Page.navigate',{url:pathToFileURL(path.join(root,'index.html')).href});for(let n=0;n<100;n++){if(await ev('!!window.HomeYear?.UI'))break;await delay(50);}await ev("localStorage.clear();localStorage.setItem('homeyear.tutorial','seen');document.querySelector('[data-testid=seed]').value='UI-A-NEW'");await click('[data-testid=new-game]');
check('search absent incl hidden controls',await ev("!document.querySelector('#search,[data-testid=search],input[type=search]')"));await click('[data-action=help]');check('help no search',await ev("!document.querySelector('dialog').textContent.includes('搜索')"));await close();
for(const [width,height,dsf]of [[1366,768,1],[1600,900,1],[1920,1080,1],[2560,1440,1],[1536,864,1.25],[1280,720,1.5]]){await c.send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:dsf,mobile:false});await delay(120);const r=await ev(`(()=>{const next=document.querySelector('[data-testid=next-week]').getBoundingClientRect(),list=document.querySelector('.market-list').getBoundingClientRect();return {width:innerWidth,height:innerHeight,center:Math.abs(next.left+next.width/2-innerWidth/2),visible:next.top>=0&&next.bottom<=innerHeight&&next.left>=0&&next.right<=innerWidth,overflow:document.documentElement.scrollWidth>innerWidth||document.documentElement.scrollHeight>innerHeight,full:[...document.querySelectorAll('.product')].filter(e=>{const r=e.getBoundingClientRect();return r.top>=list.top&&r.bottom<=list.bottom&&r.left>=list.left&&r.right<=list.right}).length,positions:{warehouse:document.querySelector('.warehouse-panel').getBoundingClientRect().left,letter:document.querySelector('.personal-letter').getBoundingClientRect().left,bulletin:document.querySelector('.bulletin').getBoundingClientRect().left}}})()`);report.layouts.push(r);check('layout centered/visible/no overflow '+width,r.center<=4&&r.visible&&!r.overflow&&r.positions.warehouse<r.positions.letter&&r.positions.letter<r.positions.bulletin,r);if(width===1366)check('new1366 at least four complete cards',r.full>=4,r.full);await shot('new-'+width+'x'+height);}
await c.send('Emulation.setDeviceMetricsOverride',{width:1366,height:768,deviceScaleFactor:1,mobile:false});
let {s,id}=holdingFixture();await importState(s);const quick=q=>`[data-action=quick-sell][data-id="${id}"][data-qty="${q}"]`;
async function exactSale(q,selector){const before=await snap(),e=new H.Engine();e.restore(before);dispatch(e,'sell',id,q);await click(selector);const after=await snap();check('exact full sale state '+id+' x'+q,JSON.stringify(after)===JSON.stringify(e.snapshot()));check('quick sale no dialog',await ev('!document.querySelector("dialog").open'));return after;}
await ev(`document.querySelector('${quick(5)}').focus()`);const previewText=await ev(`document.querySelector('[data-quick-preview="${id}"]').textContent`);check('whole-order fee visible on focus',previewText.includes('手续费 '+('¥'+(H.fee(H.channelGross(s,id,5))/100).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2}))),previewText);await exactSale(5,quick(5));await exactSale(1,quick(1));await exactSale(5,quick('all'));check('clear holding focus not next',await ev("document.activeElement.id==='warehouse-title'"));
for(const q of [1,4,5,9]){const f=holdingFixture(q);id=f.id;await importState(f.s);check('sell5 availability '+q,await ev(`document.querySelector('${quick(5)}').disabled===${q<5}`));}
await click(`[data-action=custom-sell][data-id="${id}"]`);for(const value of ['0','-1','1.5','1e2','10','100000001','']){await input(`[data-sale-input="${id}"]`,value);check('invalid custom '+value,await ev(`document.querySelector('[data-action=custom-submit][data-id="${id}"]').disabled`));}
await input(`[data-sale-input="${id}"]`,'3');await exactSale(3,`[data-action=custom-submit][data-id="${id}"]`);await ev(`document.querySelector('[data-sale-input="${id}"]').focus()`);const week=(await snap()).week;await press(' ','Space',32,2);check('quantity Space not next',(await snap()).week===week);await click('[data-testid=next-week]');check('new week clears drafts',await ev('!document.querySelector("[data-sale-input]")'));
// Native key gestures across >220ms repeats. Clearing a card must not hit its neighbour.
for(const key of ['Enter',' ']){const f=holdingFixture(9);id=f.id;await importState(f.s);await ev(`document.querySelector('${quick(1)}').focus()`);const before=await snap();await press(key,key===' '?'Space':'Enter',key===' '?32:13,3);const after=await snap();check('native held '+key+' sells once, no next',after.stats.trades===before.stats.trades+1&&after.week===before.week&&H.qtyOf(after,id)===8,{before:before.stats.trades,after:after.stats.trades,qty:H.qtyOf(after,id),active:await ev('document.activeElement.outerHTML.slice(0,350)')});await delay(260);await ev(`document.querySelector('${quick(1)}').focus()`);await press(key,key===' '?'Space':'Enter',key===' '?32:13);check('independent key gesture still sells',H.qtyOf(await snap(),id)===7);}
await importState(multi);id='rice';await ev(`document.querySelector('${quick('all')}').focus()`);const beforeClear=await snap();await press('Enter','Enter',13,3);check('held clear cannot sell neighbour', (await snap()).stats.trades===beforeClear.stats.trades+1&&(await snap()).week===beforeClear.week);check('clear focus has warehouse fallback',await ev("!!document.activeElement.closest('.warehouse-panel')"));
// Real double click second click delayed beyond old 220ms debounce.
({s,id}=holdingFixture(9));await importState(s);const xy=await ev(`(()=>{const e=document.querySelector('${quick(1)}');e.scrollIntoView({block:'center'});const r=e.getBoundingClientRect();return {x:r.left+r.width/2,y:r.top+r.height/2}})()`);const beforeDouble=await snap();for(const count of [1,2]){for(const type of ['mousePressed','mouseReleased'])await c.send('Input.dispatchMouseEvent',{type,...xy,button:'left',clickCount:count});await delay(280);}check('native double click >220ms sells once',H.qtyOf(await snap(),id)===H.qtyOf(beforeDouble,id)-1);await click(quick(1));await click(quick(1));check('normal independent clicks continue selling',H.qtyOf(await snap(),id)===6);
await importState(multi);check('all twelve current holdings accessible',await ev("document.querySelectorAll('[data-holding]').length===12"));const rngBefore=await snap();await click('[data-action=category][data-category="电子"]');await ev("document.querySelector('#view-filter').value='favorite';document.querySelector('#view-filter').dispatchEvent(new Event('change',{bubbles:true}))");check('filters do not hide warehouse',await ev("document.querySelectorAll('[data-holding]').length===12"));check('UI only state immutable',JSON.stringify(await snap())===JSON.stringify(rngBefore));await shot('full-current-filtered');
await ev(`document.querySelector('.warehouse-list').scrollTop=500;document.querySelector('[data-action=quick-sell][data-id=rice][data-qty="1"]').focus({preventScroll:true})`);const scroll=await ev("document.querySelector('.warehouse-list').scrollTop");id='rice';await exactSale(1,quick(1));check('scroll preserved and logical focus retained',await ev(`Math.abs(document.querySelector('.warehouse-list').scrollTop-${scroll})<2&&!!document.activeElement.closest('.warehouse-panel')`));await shot('current-sale');
// Reviewer P2: assert exact logical product + entrance, not merely warehouse containment.
const activeKey=()=>ev('document.activeElement.dataset.focus||document.activeElement.id');
({s,id}=holdingFixture(9));await importState(s);await ev(`document.querySelector('${quick(1)}').focus()`);await exactSale(1,quick(1));check('P2 same product same sell1 button',await activeKey()==='sell-'+id+'-1');
({s,id}=holdingFixture(9));await importState(s);await ev(`document.querySelector('${quick(5)}').focus()`);await exactSale(5,quick(5));check('P2 disabled sell5 returns same-product sell1',H.qtyOf(await snap(),id)===4&&await activeKey()==='sell-'+id+'-1');
({s,id}=holdingFixture(9));await importState(s);await ev(`document.querySelector('[data-focus="custom-${id}"]').focus()`);await click(`[data-action=custom-sell][data-id="${id}"]`);await input(`[data-sale-input="${id}"]`,'6');await ev(`document.querySelector('[data-focus="submit-${id}"]').focus()`);await exactSale(6,`[data-focus="submit-${id}"]`);check('P2 disabled custom confirmation returns same-product input',await activeKey()==='input-'+id&&await ev(`document.querySelector('[data-focus="submit-${id}"]').disabled`));
const detailE=new H.Engine('UI-A-NEW');dispatch(detailE,'buy','rice',5);await importState(detailE.snapshot());await ev('document.querySelector("[data-focus=detail-rice]").focus()');await click('[data-focus=detail-rice]');await click('[data-testid=trade-submit]');await close();check('P2 rice detail sell1 close same detail entrance',H.qtyOf(await snap(),'rice')===4&&await activeKey()==='detail-rice');
const heldIds=H.heldProducts().filter(p=>H.qtyOf(multi,p.id)).map(p=>p.id);
for(const index of [0,Math.floor(heldIds.length/2),heldIds.length-1]){for(const entrance of ['quick','detail']){await importState(multi);id=heldIds[index];const expected=heldIds[index+1]||heldIds[index-1];if(entrance==='quick'){await ev(`document.querySelector('${quick('all')}').focus()`);await exactSale(H.qtyOf(multi,id),quick('all'));check('P2 '+entrance+' clear position '+index,await activeKey()==='sell-'+expected+'-1');}else{await ev(`document.querySelector('[data-focus="detail-${id}"]').focus()`);await click(`[data-focus="detail-${id}"]`);await click('[data-action=quantity][data-qty=max]');await click('[data-testid=trade-submit]');await close();check('P2 '+entrance+' clear position '+index,H.qtyOf(await snap(),id)===0&&await activeKey()==='detail-'+expected);}}}
({s,id}=holdingFixture(1));await importState(s);await ev(`document.querySelector('[data-focus="detail-${id}"]').focus()`);await click(`[data-focus="detail-${id}"]`);await click('[data-testid=trade-submit]');await close();check('P2 final detail clear returns warehouse title',await activeKey()==='warehouse-title');await shot('p2-detail-clear-focus');
// Off-sale channel and week52, no53; choose legitimate absent fixture after actual rotation.
({s,id}=holdingFixture(9));const offEngine=new H.Engine();offEngine.restore(s);while(offEngine.snapshot().listing.includes(id))dispatch(offEngine,'next');await importState(offEngine.snapshot());await exactSale(5,quick(5));await shot('off-sale');
// Persistence failure is post-commit; retry only save, never the sale.
for(const error of ['SecurityError','QuotaExceededError']){({s,id}=holdingFixture(9));await importState(s);await ev(`window.originalSet=Storage.prototype.setItem;Storage.prototype.setItem=function(){throw new DOMException('QA save denied',${JSON.stringify(error)})}`);await exactSale(1,quick(1));check('save failure toast accurate '+error,await ev("document.querySelector('#toasts').textContent.includes('已卖出')&&document.querySelector('#toasts').textContent.includes('未保存')"));const a=await snap();await click('[data-action=settings]');await ev('window.oldURL=URL.createObjectURL;URL.createObjectURL=function(blob){window.exported=blob.text();return window.oldURL(blob)}');await click('[data-action=export]');const exported=await ev('window.exported');check('export available after save failure '+error,JSON.stringify(JSON.parse(exported))===JSON.stringify(a));await ev('URL.createObjectURL=window.oldURL');await close();await ev('Storage.prototype.setItem=window.originalSet');await click('[data-testid=save]');check('save retry no new transaction '+error,JSON.stringify(await snap())===JSON.stringify(a)&&await ev('JSON.stringify(HomeYear.UI.snapshot())===localStorage.getItem("homeyear.save.v11")'));}
await click('[data-action=settings]');await click('[data-setting=autoSave]');await close();const raw=await ev('localStorage.getItem("homeyear.save.v11")');await exactSale(1,quick(1));check('autosave off accurate pending status',await ev("document.body.textContent.includes('进度未保存')")&&raw===await ev('localStorage.getItem("homeyear.save.v11")'));await click('[data-action=settings]');await click('[data-setting=autoSave]');await close();
const endE=new H.Engine();endE.restore(holdingFixture().s);while(endE.snapshot().week<52)dispatch(endE,'next');const absent=endE.snapshot().listing.includes(id);s=endE.snapshot();id=Object.keys(s.inventory).find(x=>s.inventory[x].qty);if(s.listing.includes(id)){const incoming=H.products.find(p=>!s.listing.includes(p.id)&&H.listingCovers(s.listing.filter(x=>x!==id).concat(p.id)));if(!incoming)throw Error('no legal week52 off-sale fixture');s.listing=H.products.map(p=>p.id).filter(x=>s.listing.includes(x)&&x!==id||x===incoming.id);s.absence[id]=1;s.onStreak[id]=0;s.absence[incoming.id]=0;s.onStreak[incoming.id]=1;H.validate(s);}check('week52 fixture actually off-sale',!s.listing.includes(id));await importState(s);await exactSale(H.qtyOf(s,id),quick('all'));await click('[data-testid=next-week]');check('week52 confirm without end',(await snap()).status==='playing'&&(await snap()).week===52);await close();check('week52 cancel no result',(await snap()).status==='playing');await click('[data-testid=next-week]');await click('[data-testid=confirm-yes]');check('week52 ends exactly once',(await snap()).status==='ended'&&(await snap()).week===52);await close();const ended=await snap();await click('[data-testid=next-week]');check('ended next is result only',JSON.stringify(await snap())===JSON.stringify(ended));
// Held body Space advances only once; native save/expand buttons never advance weeks.
({s,id}=holdingFixture(9));await importState(s);await ev('document.activeElement.blur()');const bodyWeek=(await snap()).week;await press(' ','Space',32,3);check('body Space held advances once',(await snap()).week===bodyWeek+1);await close();
for(const key of ['Enter',' ']){await ev("document.querySelector('[data-testid=save]').focus()");const w=(await snap()).week;await press(key,key===' '?'Space':'Enter',key===' '?32:13,2);check('native save '+key+' no next',(await snap()).week===w);}
for(const key of ['Enter',' ']){await importState(multi);id='rice';await ev(`document.querySelector('${quick('all')}').focus()`);const a=await snap();await press(key,key===' '?'Space':'Enter',key===' '?32:13,3);check('clear held '+key+' cannot sell next card',(await snap()).stats.trades===a.stats.trades+1&&(await snap()).week===a.week);}
await importState(holdingFixture(9).s);id=holdingFixture(9).id;const rapid=await snap();await ev(`document.querySelector('${quick(1)}').click();document.querySelector('${quick(5)}').click()`);await delay(260);check('rapid cross-button gesture respects submission guard',(await snap()).stats.trades===rapid.stats.trades+1);
// Long valid amounts + full current holdings under all supported desktop sizes.
const huge=H.clone(multi);huge.cash+=100000000000;huge.stats.grants+=100000000000;H.record(huge);H.validate(huge);await importState(huge);
for(const [width,height]of [[1366,768],[1600,900],[1920,1080],[2560,1440],[1536,864],[1280,720]]){await c.send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:false});const r=await ev(`(()=>{const es=[...document.querySelectorAll('.topbar>.brand-chip,.topbar>.year-progress,.topbar>.metrics,.topbar>.top-actions')].map(e=>e.getBoundingClientRect());return {overflow:document.documentElement.scrollWidth>innerWidth,overlap:es.some((a,i)=>es.slice(i+1).some(b=>a.left<b.right&&b.left<a.right&&a.top<b.bottom&&b.top<a.bottom)),next:document.querySelector('[data-testid=next-week]').getBoundingClientRect().bottom<=innerHeight}})()`);check('long amounts/full warehouse '+width,!r.overflow&&!r.overlap&&r.next,r);await shot('full-current-long-'+width);}
await c.send('Emulation.setDeviceMetricsOverride',{width:1366,height:768,deviceScaleFactor:1,mobile:false});
// Find natural ongoing + personal information without altering news.
let newsState;for(let n=0;n<30&&!newsState;n++){const e=new H.Engine('UI-A-NEWS-'+n);for(let w=1;w<52;w++){dispatch(e,'next');const t=e.snapshot();if(t.news.some(n=>n.kind==='personal')&&t.news.filter(n=>n.kind==='ongoing').length>=2){newsState=t;break;}}}if(!newsState)throw Error('no personal/ongoing fixture');await importState(newsState);check('personal once central and ongoing once right',await ev("(()=>{const s=HomeYear.UI.snapshot();return s.news.filter(n=>n.kind==='personal').every(n=>document.querySelector('.personal-letter').textContent.includes(n.title)&&!document.querySelector('.bulletin').textContent.includes(n.title))&&s.news.filter(n=>n.kind==='ongoing').length===document.querySelectorAll('[data-news-kind=ongoing]').length})()"));check('listing no percentage',await ev("[...document.querySelectorAll('[data-news-kind=listing]')].every(el=>!/%/.test(el.textContent))"));check('other news percentages bind actual name and change',await ev("(()=>{const H=HomeYear,s=H.UI.snapshot();return [...document.querySelectorAll('[data-news-kind]:not([data-news-kind=listing])')].every(el=>{const n=s.news.find(n=>n.kind===el.dataset.newsKind&&el.textContent.includes(n.title));if(!n||!n.productId)return true;const b=H.changeBps(H.quoteOf(s,n.productId));return el.textContent.includes(H.holding(n.productId).name+' · 本周 '+(b>=0?'+':'')+(b/100).toFixed(1)+'%')})})()"));await click('.personal-letter summary');await shot('personal-expanded-ongoing');
for(const [width,height] of [[1000,720],[650,720]]){await c.send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:false});check('small-screen horizontal no overflow '+width,await ev('document.documentElement.scrollWidth<=innerWidth'));await shot('fallback-'+width);}
check('no errors or external requests',!report.errors.length&&!report.external.length,{errors:report.errors,external:report.external});
}catch(e){report.fatal=e.stack;console.error(e);}finally{if(edge)await edge.cleanup();report.summary={passed:report.checks.filter(x=>x.pass).length,failed:report.checks.filter(x=>!x.pass).length};fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({summary:report.summary,layouts:report.layouts,fatal:report.fatal},null,2));if(report.fatal||report.summary.failed)process.exitCode=1;}})();
